# Generated by Django 5.2.4 on 2025-08-01 00:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=24)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ImageField(upload_to='profile_pics')),
            ],
        ),
    ]
