services:
  web:
    build:
      context: ../
      dockerfile: docker-config/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    environment:
      - DEBUG=True
      - DATABASE=sqlite

volumes:
  sqlite_data: