name: Run Tests

on:
  workflow_dispatch:

jobs:
  pytest:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pipx
        run: python -m pip install --upgrade pipx

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run python manage.py test api.tests
